///////////////////////////////////////////////////////////
//  ConcreteMessageFactory.cs
//  Implementation of the Class ConcreteMessageFactory
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:07
//  Original author: Andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using chatpkg;
namespace chatpkg {
	public class ConcreteMessageFactory : MessageFactory {

		public ConcreteMessageFactory(){

		}

		~ConcreteMessageFactory(){

		}

		/// 
		/// <param name="str"></param>
		public override ChatLine GetAutoMessage(string str, User u){
            switch (str)
            {
                case "1":
                    return new ChatLine("Hello!", u);
                case "2":
                    return new ChatLine("Goodbye!", u);
                case "3":
                    return new ChatLine("How are you?", u);
                default:
                    return new ChatLine("", u);
            }
		}

	}//end ConcreteMessageFactory

}//end namespace chatpkg