///////////////////////////////////////////////////////////
//  MessageFactory.cs
//  Implementation of the Class MessageFactory
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:10
//  Original author: Andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace chatpkg {
	public abstract class MessageFactory {

		public MessageFactory(){

		}

		~MessageFactory(){

		}

		/// 
		/// <param name="str"></param>
		public abstract ChatLine GetAutoMessage(string str, User u);

	}//end MessageFactory

}//end namespace chatpkg