///////////////////////////////////////////////////////////
//  ChatRoom.cs
//  Implementation of the Class ChatRoom
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:32
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using chatpkg;
namespace chatpkg {
	public class ChatRoom {

		private string name;
		public List<ChatLine> chatLines;

		public ChatRoom(){

		}

        public ChatRoom(string name, List<ChatLine> chatLines)
        {
            this.name = name;
            this.chatLines = chatLines;
        }

        ~ChatRoom(){

		}

        public void AddChatLine(ChatLine chatLine)
        {
            try
            {
                chatLines.Add(chatLine);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

        public void RemoveChatLine(ChatLine chatLine)
        {
            try
            {
                chatLines.Remove(chatLine);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

        public override string ToString()
        {
            return Name;
        }

        public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

	}//end ChatRoom

}//end namespace chatpkg