///////////////////////////////////////////////////////////
//  ChatLine.cs
//  Implementation of the Class ChatLine
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:43:54
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using chatpkg;
namespace chatpkg {
	public class ChatLine {

		private string content;
		public User user;

		public ChatLine(){

		}

        public ChatLine(string content, User user)
        {
            this.content = content;
            this.user = user;
        }

        ~ChatLine(){

		}

		public string Content{
			get{
				return content;
			}
			set{
				content = value;
			}
		}


        public string Username
        {
            get { return user.FirstName + " " + user.LastName; }
        }

    }//end ChatLine

}//end namespace chatpkg