///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:49
//  Original author: sasa.devic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using chatpkg;
namespace chatpkg {
	public class User {

		private string firstName;
		private string lastName;
		public ConcreteMessageFactory concreteMessageFactory;

		public User(){

		}

        public User(string firstName, string lastName, ConcreteMessageFactory concreteMessageFactory)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.concreteMessageFactory = concreteMessageFactory;
        }

        ~User(){

		}

		public string FirstName{
			get{
				return firstName;
			}
			set{
				firstName = value;
			}
		}

		public string LastName{
			get{
				return lastName;
			}
			set{
				lastName = value;
			}
		}

        public override string ToString()
        {
            return FirstName + " " + LastName;
        }
    }//end User

}//end namespace chatpkg