///////////////////////////////////////////////////////////
//  Command.cs
//  Implementation of the Class Command
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:06
//  Original author: Andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace chatpkg {
	public abstract class Command {

		public Command(){

		}

		~Command(){

		}

		public abstract void Execute();

		public abstract void UnExecute();

	}//end Command

}//end namespace chatpkg