///////////////////////////////////////////////////////////
//  LineCommand.cs
//  Implementation of the Class LineCommand
//  Generated by Enterprise Architect
//  Created on:      04-jun-2023 09:37:09
//  Original author: Andrej
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using chatpkg;
namespace chatpkg {
	public abstract class LineCommand : Command {

		protected ChatRoom chatRoom;
		protected ChatLine chatLine;

		public LineCommand(){

		}

        protected LineCommand(ChatRoom chatRoom, ChatLine chatLine) : base()
        {
            this.chatRoom = chatRoom;
            this.chatLine = chatLine;
        }

        ~LineCommand(){

		}

	}//end LineCommand 

}//end namespace chatpkg